export const STATES = {
  WAIT_STUDENT_ANSWER: "WAIT_STUDENT_ANSWER",
  WAIT_MATERIAL: "WAIT_MATERIAL",
  WAIT_MORE_FILES: "WAIT_MORE_FILES",
  WAIT_FILES: "WAIT_FILES",
  PRINT_OPTIONS: "PRINT_OPTIONS",
};
